### DISCUSSION TITLE
wasmlabs landpage `overflow-x`.

### DISCUSSION THREAD

**Discussion by X7md** [vmware-labs/.github#2] [General]
Hi there, I noticed that landpage have `overflow-x`  issue, in small screen...
 
![image](https://user-images.githubusercontent.com/54203033/197691980-c4dd9cde-c73f-49db-90d2-11091ff9ec18.png)
 
and could be easily fix by add:
```css
[aria-labelled-by="latest-projects"] > .section {
    overflow-x: auto;
} 
```
so the browser will make it  **scrollable**.

Preview for my fix:
![image](https://user-images.githubusercontent.com/54203033/197692363-b47fc4cb-5d2d-41f0-975a-ea6727145165.png)
